import random 
import lorem
import bcrypt

family_names = ["Aaron",
"Abbott",
"Abel",
"Abell",
"Abernathy",
"Abney",
"Abraham",
"Abrams",
"Abreu",
"Acevedo",
"Acker",
"Ackerman",
"Acosta",
"Acuna",
"Adair",
"Adam",
"Adame",
"Adams",
"Adamson",
"Adcock",
"Addison",
"Adkins",
"Adler",
"Agee",
"Agnew",
"Aguiar",
"Aguilar",
"Aguilera",
"Aguirre",
"Ahern",
"Ahmed",
"Ahrens",
"Aiello",
"Aiken",
"Ainsworth",
"Akers",
"Akin",
"Akins",
"Alaniz",
"Alarcon",
"Alba",
"Albers",
"Albert",
"Albertson",
"Albrecht",
"Albright",
"Alcala",
"Alcorn",
"Alderman",
"Aldrich",
"Aldridge",
"Aleman",
"Alexander"]

first_names = ["Dale",
"Beau",
"Cliff",
"Timothy",
"Raphael",
"Brain",
"Mauro",
"Luke",
"Myron",
"Omar",
"Reynaldo",
"Major",
"Clinton",
"Nolan",
"Raymond",
"Lucien",
"Carey",
"Winfred",
"Dan",
"Abel",
"Elliott",
"Brent",
"Chuck",
"Dirk",
"Tod",
"Emerson",
"Dewey",
"Scot",
"Enrique",
"Al",
"Beatrice",
"Brandy",
"Kathy",
"Jane",
"Marcy",
"Shelly",
"Lucy",
"Cathy",
"Joanna",
"Doris",
"Lindsay",
"Staci",
"Shelia",
"Rosanne",
"Rebecca",
"Luz",
"Flora",
"Rosalie",
"Karla",
"Phoebe",
"Meagan",
"Virginia",
"Amanda",
"Katy",
"Karla",
"Deanne",
"Pearl",
"Christi",
"Victoria",
"Ola",
"Alexandra",
"Marina",
"Lorraine",
"Sybil",
"Adeline",
"Taylor",
"Anita",
"Aurora",
"Neva",
"Alisha",
"Maria",
"Erna",
"Gwendolyn",
"Brenda",
"Bethany",
"Sybil",
"Earline",
"June",
"Brandy",
"Sue"]


birthdays = ["1923-10-16",
"1938-11-13",
"1939-06-04",
"1941-05-02",
"1942-11-12",
"1945-06-14",
"1945-09-24",
"1946-08-28",
"1947-08-16",
"1951-01-02",
"1951-08-03",
"1955-11-12",
"1965-05-03",
"1967-06-10",
"1971-07-01",
"1971-11-11",
"1973-09-18",
"1976-12-02",
"1981-01-14",
"1981-08-12",
"1987-03-30",
"1993-01-06",
"1994-09-15",
"1994-12-04",
"1999-02-11"]


genre = ['Homme','Femme','Autre']

pays = ["Afghanistan",
"Albania",
"Algeria",
"Andorra",
"Angola",
"Antigua & Deps",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bhutan",
"Bolivia",
"Bosnia Herzegovina",
"Botswana",
"Brazil",
"Brunei",
"Bulgaria",
"Burkina",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Central African Rep",
"Chad",
"Chile",
"China",
"Colombia",
"Comoros",
"Congo",
"Congo {Democratic Rep}",
"Costa Rica",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic",
"East Timor",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Fiji",
"Finland",
"France",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Ghana",
"Greece",
"Grenada",
"Guatemala",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Honduras",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland {Republic}",
"Israel",
"Italy",
"Ivory Coast",
"Jamaica",
"Japan",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"Korea North",
"Korea South",
"Kosovo",
"Kuwait",
"Kyrgyzstan",
"Laos",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macedonia",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Mauritania",
"Mauritius",
"Mexico",
"Micronesia",
"Moldova",
"Monaco",
"Mongolia",
"Montenegro",
"Morocco",
"Mozambique",
"Myanmar, {Burma}",
"Namibia",
"Nauru",
"Nepal",
"Netherlands",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Poland",
"Portugal",
"Qatar",
"Romania",
"Russian Federation",
"Rwanda",
"St Kitts & Nevis",
"St Lucia",
"Saint Vincent & the Grenadines",
"Samoa",
"San Marino",
"Sao Tome & Principe",
"Saudi Arabia",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"South Sudan",
"Spain",
"Sri Lanka",
"Sudan",
"Suriname",
"Swaziland",
"Sweden",
"Switzerland",
"Syria",
"Taiwan",
"Tajikistan",
"Tanzania",
"Thailand",
"Togo",
"Tonga",
"Trinidad & Tobago",
"Tunisia",
"Turkey",
"Turkmenistan",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Vatican City",
"Venezuela",
"Vietnam",
"Yemen",
"Zambia",
"Zimbabwe"]


email = ["Tarynjittery@yahoo.fr",
"Noahglorious@yahoo.fr",
"selfishRaquel47@charter.net",
"fancyLuke@bigpond.net.au",
"franticNaomi@rambler.ru",
"Anndizzy@gmx.de",
"carefulTiffany57@terra.com.br",
"gorgeousJared68@live.nl",
"creepyDeborah94@gmx.de",
"amusedSuzanne89@aol.com",
"Denisecheerful@t-online.de",
"sillyKara46@live.it",
"wide-eyedDaisy@hetnet.nl",
"awfulKara52@t-online.de",
"cleverJose61@hotmail.de",
"powerfulDeborah@terra.com.br",
"defiantColleen24@yahoo.com.au",
"Erinuptight@hetnet.nl",
"Marccautious@ig.com.br",
"itchyPhilip@live.com.au",
"thankfulCarrie@live.com.au",
"Jonathonrepulsive@chello.nl",
"distinctWillie@skynet.be",
"averageMelanie@yahoo.ca",
"tastyBarry@yandex.ru",
"Sophialong@uol.com.br",
"homelessVanessa19@cox.net",
"gorgeousBrent@yahoo.in",
"Edwinhurt@club-internet.fr",
"poorAshlee@googlemail.com",
"blue-eyedTanya98@comcast.net",
"Robertoinnocent@sfr.fr",
"cleverBeth@gmx.net",
"goodAaron57@wanadoo.fr",
"puzzledJay86@msn.com",
"Meaganexcited@zonnet.nl",
"dangerousMarie@zonnet.nl",
"Meaganterrible@optusnet.com.au",
"defiantTammy89@yahoo.co.uk",
"Carolinefancy@gmail.com",
"realJermaine79@hotmail.co.uk",
"annoyedAdriana0@yahoo.co.id",
"cleanVirginia@tin.it",
"Leahcheerful@mail.ru",
"Codypuzzled@skynet.be",
"muddyAmber78@sympatico.ca",
"wittyKeith84@juno.com",
"fragileDanny38@frontiernet.net",
"cleanDominic0@yahoo.de",
"perfectRyan@orange.fr",
"aggressiveMaggie@bigpond.net.au",
"badEdward7@yahoo.com.br",
"Carlacondemned@free.fr",
"distinctJanelle81@laposte.net",
"tenseSabrina66@sfr.fr",
"badVirginia@libero.it",
"glamorousAllison12@yahoo.de",
"Isaacelated@live.nl",
"Tracydistinct@live.com.au",
"alertArmando66@bigpond.com",
"colorfulRoss@gmail.com",
"giftedRebekah@hotmail.de",
"badTristan@sympatico.ca",
"courageousErin@yandex.ru",
"Darrylcute@libero.it",
"fragileJohnny@aim.com",
"fancyDaisy@terra.com.br",
"cleanDeborah85@juno.com",
"uninterestedAlyssa85@gmail.com",
"funnyPedro@yahoo.es",
"hungryCarla57@ymail.com",
"elatedKaren@neuf.fr",
"Patrickconcerned@optusnet.com.au",
"grotesqueKendra51@blueyonder.co.uk",
"fairJeffrey@web.de",
"thankfulSpencer51@yandex.ru",
"Elizabethclean@yahoo.co.id",
"aggressiveAnne@tiscali.it",
"Dominicmysterious@alice.it",
"proudDesiree10@uol.com.br",
"plainNicole17@rediffmail.com",
"concernedErica@blueyonder.co.uk",
"Austinstupid@yahoo.com.au",
"tastySophia@mac.com",
"cheerfulMelanie@tin.it",
"Loganfierce@sbcglobal.net",
"talentedRonald@virgilio.it",
"jitteryGrant86@virgilio.it",
"Brendanice@bluewin.ch",
"Jefferyjittery@live.it",
"angryKatherine25@aim.com",
"Jonathanbad@mail.com",
"Leahcooperative@sfr.fr",
"jealousKaitlin@tiscali.it",
"curiousAaron37@blueyonder.co.uk",
"Edwinfrail@live.it",
"openEduardo@planet.nl",
"gentleMelody@yahoo.co.in",
"cuteSara70@terra.com.br",
"wildLinda@hotmail.com"]


phone = random.randint(1000000, 999999999999999)


code_postal = random.randint(10000, 9999999999)

travail = ["Agronome",
"Animalier/Animalière de laboratoire",
"Astrophysicien/Astrophysicienne",
"Bio-informaticien/Bio-informaticienne",
"Biologiste en environnement",
"Chercheur/Chercheuse en biologie",
"Chercheur/Chercheuse en chimie",
"Chercheur/Chercheuse en physique",
"Démographe",
"Enseignant-chercheur/Enseignante-chercheuse",
"Ethnologue",
"Ingénieur/Ingénieure brevets",
"Ingénieur/Ingénieure R&D en énergies renouvelables",
"Ingénieur/Ingénieure R&D en agroalimentaire",
"Linguiste",
"Océanologue",
"Pharmacien/Pharmacienne",
"Sociologue",
"Zoologiste"]

grade =  ['Chargé de recherche de classe normale (CRCN)','Chargé de recherche hors classe (CRHC)',
'directeur de recherche de 2ème classe (DR2)',
'directeur de recherche de 1ère classe (DR1)', 
'directeur de recherche de classe exceptionnelle (DRCE)']

structure = ['Laboratoire','Université/École','CNRS et autres Organismes']
college = ["Community College of the Air Force",
"Alabama A & M University",
"University of Alabama at Birmingham",
"Amridge University",
"University of Alabama at Huntsville",
"Alabama State University",
"The University of Alabama",
"Central Alabama Community College",
"Athens State University",
"Auburn University-Montgomery",
"Auburn University Main Campus",
"Birmingham Southern College",
"Chattahoochee Valley Community College",
"Concordia College Alabama",
"Enterprise State Community College",
"James H. Faulkner State Community College",
"Faulkner University",
"Gadsden Business College",
"Gadsden State Community College",
"George C Wallace Community College",
"Wallace State Community College - Hanceville",
"George Corley Wallace State Community College - Selma",
"Huntingdon College",
"Heritage Christian University",
"J.F. Drake State Community and Technical College",
"J F Ingram State Technical College",
"Jacksonville State University",
"Jefferson Davis Community College",
"Jefferson State Community College",
"Calhoun Community College"]


s_d_afiiliation = random.choice(structure) + " " + random.choice(college)

biographie = ["Web scholar. Hipster-friendly pop culture maven. Proud internet expert.",
"Analyst. Subtly charming twitter geek. Lifelong travel expert. General beer trailblazer.",
"Troublemaker. Pop culture scholar. Subtly charming bacon maven. Friendly travel lover. Proud explorer. Reader.",
"Certified pop culture advocate. Analyst. Travel junkie. Social media fanatic. Student. Lifelong beer nerd.",
"Amateur tv fan. Pop culture evangelist. Web maven. Entrepreneur. Award-winning bacon fanatic.",
"Creator. Zombie trailblazer. Coffee advocate. Freelance entrepreneur. Evil social media aficionado.",
"Wannabe pop culture fanatic. Web enthusiast. General social media evangelist. Foodaholic. Alcohol specialist.",
"Friendly web buff. Amateur twitter aficionado. Social media guru. Zombie fanatic. Communicator. Total bacon lover. Coffee specialist. Organizer.",
"Coffee fanatic. Unapologetic twitter maven. Devoted bacon aficionado. Tv evangelist. Zombieaholic.",
"Evil zombie nerd. Tv aficionado. Coffee evangelist. Friendly travel junkie. Internet practitioner.",
"Prone to fits of apathy. Problem solver. Twitter buff. Wannabe music advocate.",
"Pop culture evangelist. Avid communicator. General student. Alcohol fanatic. Travel specialist.",
"Incurable social media junkie. Tv specialist. Introvert. Avid zombie expert. Troublemaker.",
"Avid travel lover. Subtly charming social media fanatic. Thinker. Unapologetic beer geek. Tv aficionado. Food guru. Devoted internet maven.",
"Internet expert. Communicator. Coffee trailblazer. Tv nerd. Hipster-friendly zombie maven."]




thematique = lorem.sentence()

nom_d_utilisateur = ["quality",
"common",
"height",
"disappear",
"gnat",
"strum",
"pass",
"raisins",
"hidden",
"collarbone",
"secondhand",
"dodgeball",
"binnacle",
"piston",
"microsoft",
"wally",
"complaint",
"outraged",
"garboard",
"guilty",
"universe",
"duct",
"digital",
"mainmast",
"bra",
"packed",
"dell",
"truffle",
"brain",
"pear",
"station",
"saveloy",
"ream",
"fisherman",
"oyster",
"beer",
"massive",
"hawsehole",
"upbeat",
"consonant",
"child",
"vulgar",
"clove",
"cagey",
"aircraft",
"crochet",
"seem",
"louse",
"squelch",
"frazzled",
"playful",
"western",
"none",
"page",
"cup",
"fasten",
"busstop",
"earnest",
"stairs",
"depict",
"trot",
"ledger",
"onto",
"heavy",
"sarong",
"terms",
"wanting",
"yule",
"alligator",
"blazer",
"currant",
"economic",
"boeing",
"rhetorical",
"lecture",
"cuff"]

passwd = str(random.choice(nom_d_utilisateur)).encode('utf-8')

print("INSERT INTO chercheurs('nom', 'prenom', 'date_de_naissance', 'genre', 'pays', 'email', 'num_tel', 'code_postal'," +
" 'travail', 'grade', 'structure', 'biographie', 'thematique', 'cv', 'nom_d_utilisateur', 'mot_de_passe')" +  
 "VALUES(" + '"' +random.choice(family_names)+ '"' + "," +  '"'  +random.choice(first_names)+ '"'  +"," 
 +  '"' +random.choice(birthdays) + '"' + "," +  '"' +random.choice(genre)+ '"' +"," +  '"' +random.choice(pays)+ '"'
  + "," +  '"' +random.choice(email)+ '"' +","+  '"' +str(phone)+ '"' +","+  '"' +str(code_postal) + '"' +","+  '"' 
  + random.choice(travail)+ '"' 
 +","+ '"' +random.choice(grade)+ '"' +","+ '"' +
 random.choice(s_d_afiiliation)+ '"' +","+ '"' +random.choice(biographie)+ '"' + "," + '"' + random.choice(thematique)+ '"' + "," 
 + '"' +"cv/exemple.pdf" + '"' + "," + '"' +
 random.choice(nom_d_utilisateur) + '"' + "," + '"' + str(bcrypt.hashpw(passwd, bcrypt.gensalt()))+")")